services:
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:9.0.1
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - ES_JAVA_OPTS=-Xms4g -Xmx4g
  #     - xpack.security.enabled='false'
  #     - ELASTICSEARCH_PASSWORD='P@ssw0rd'
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   volumes:
  #     - elasticsearch_data:/usr/share/elasticsearch/data
  #   restart: unless-stopped
  #
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:9.0.1
  #   container_name: kibana
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #     # - ELASTICSEARCH_USER=elastic
  #     # - ELASTICSEARCH_PASSWORD=changeme
  #   volumes:
  #     - ./kibana.yml:/usr/share/kibana/config/kibana.yml
  #   depends_on:
  #     - elasticsearch
  #   restart: unless-stopped

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      # - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=none
    restart: unless-stopped

volumes:
  # elasticsearch_data:
  neo4j_data:
  neo4j_logs:

